// Code generated by nimona.io/tools/codegen. DO NOT EDIT.

package blob

import (
	chore "nimona.io/pkg/chore"
	object "nimona.io/pkg/object"
)

type (
	Chunk struct {
		Metadata object.Metadata `nimona:"@metadata:m"`
		Data     []byte          `nimona:"data:d"`
	}
	Blob struct {
		Metadata object.Metadata `nimona:"@metadata:m"`
		Chunks   []chore.Hash    `nimona:"chunks:as"`
	}
)

func (e *Chunk) Type() string {
	return "nimona.io/Chunk"
}

func (e *Blob) Type() string {
	return "nimona.io/Blob"
}
