// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/geoah/genny

package blob

import (
	"sync"
)

type (
	requests string // nolint
	// RequestsMap -
	RequestsMap struct {
		m sync.Map
	}
)

// NewRequestsMap constructs a new SyncMap
func NewRequestsMap() *RequestsMap {
	return &RequestsMap{}
}

// GetOrPut -
func (m *RequestsMap) GetOrPut(k string, v *request) (*request, bool) {
	nv, ok := m.m.LoadOrStore(k, v)
	return nv.(*request), ok
}

// Put -
func (m *RequestsMap) Put(k string, v *request) {
	m.m.Store(k, v)
}

// Get -
func (m *RequestsMap) Get(k string) (*request, bool) {
	i, ok := m.m.Load(k)
	if !ok {
		return nil, false
	}

	v, ok := i.(*request)
	if !ok {
		return nil, false
	}

	return v, true
}

// Delete -
func (m *RequestsMap) Delete(k string) {
	m.m.Delete(k)
}

// Range -
func (m *RequestsMap) Range(i func(k string, v *request) bool) {
	m.m.Range(func(k, v interface{}) bool {
		return i(k.(string), v.(*request))
	})
}

// ListKeys -
func (m *RequestsMap) ListKeys() []string {
	vs := []string{}
	m.m.Range(func(k, v interface{}) bool {
		vs = append(vs, k.(string))
		return true
	})
	return vs
}

// ListValues -
func (m *RequestsMap) ListValues() []*request {
	vs := []*request{}
	m.m.Range(func(k, v interface{}) bool {
		vs = append(vs, v.(*request))
		return true
	})
	return vs
}
