// Code generated by nimona.io/tools/objectify. DO NOT EDIT.

// +build !generate

package exchange

import (
	"nimona.io/pkg/crypto"
	"nimona.io/pkg/object"
)

const (
	ObjectForwardRequestType = "/object-forward-request"
)

// ToObject returns a f12n object
func (s ObjectForwardRequest) ToObject() *object.Object {
	o := object.New()
	o.SetType(ObjectForwardRequestType)
	if s.Recipient != "" {
		o.SetRaw("recipient", s.Recipient)
	}
	if s.FwObject != nil {
		o.SetRaw("fwObject", s.FwObject)
	}
	if s.Signature != nil {
		o.SetRaw("@signature", s.Signature)
	}
	return o
}

// FromObject populates the struct from a f12n object
func (s *ObjectForwardRequest) FromObject(o *object.Object) error {
	if v, ok := o.GetRaw("recipient").(string); ok {
		s.Recipient = v
	}
	if v, ok := o.GetRaw("fwObject").(*object.Object); ok {
		s.FwObject = v
	}
	if v, ok := o.GetRaw("@signature").(*crypto.Signature); ok {
		s.Signature = v
	} else if v, ok := o.GetRaw("@signature").(*object.Object); ok {
		s.Signature = &crypto.Signature{}
		s.Signature.FromObject(v)
	}
	return nil
}

// GetType returns the object's type
func (s ObjectForwardRequest) GetType() string {
	return ObjectForwardRequestType
}
