// Code generated by nimona.io/tools/objectify. DO NOT EDIT.

// +build !generate

package exchange

import (
	"nimona.io/pkg/crypto"
	"nimona.io/pkg/object"
)

const (
	ObjectRequestType = "/object-request"
)

// ToObject returns a f12n object
func (s ObjectRequest) ToObject() *object.Object {
	o := object.New()
	o.SetType(ObjectRequestType)
	if s.RequestID != "" {
		o.SetRaw("requestID", s.RequestID)
	}
	if s.ID != "" {
		o.SetRaw("id", s.ID)
	}
	if s.Signature != nil {
		o.SetRaw("@signature", s.Signature)
	}
	if s.Signer != nil {
		o.SetRaw("@signer", s.Signer)
	}
	return o
}

// FromObject populates the struct from a f12n object
func (s *ObjectRequest) FromObject(o *object.Object) error {
	if v, ok := o.GetRaw("requestID").(string); ok {
		s.RequestID = v
	}
	if v, ok := o.GetRaw("id").(string); ok {
		s.ID = v
	}
	if v, ok := o.GetRaw("@signature").(*crypto.Signature); ok {
		s.Signature = v
	} else if v, ok := o.GetRaw("@signature").(*object.Object); ok {
		s.Signature = &crypto.Signature{}
		s.Signature.FromObject(v)
	}
	if v, ok := o.GetRaw("@signer").(*crypto.Key); ok {
		s.Signer = v
	} else if v, ok := o.GetRaw("@signer").(*object.Object); ok {
		s.Signer = &crypto.Key{}
		s.Signer.FromObject(v)
	}
	return nil
}

// GetType returns the object's type
func (s ObjectRequest) GetType() string {
	return ObjectRequestType
}
