run:
  skip-dirs:
    - vendor
  skip-files:
    - .*_generated.go
    - .*_mock.go
    - .*_mock_test.go

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 20
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  lll:
    line-length: 80
  goimports:
    local-prefixes: nimona.io

issues:
  max-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude:
    - "declaration of \"err\" shadows"
