run:
  skip-dirs:
    - vendor
  skip-files:
    - .*_generated.go
    - .*_mock.go
    - .*_mock_test.go

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  lll:
    line-length: 80
  goimports:
    local-prefixes: nimona.io

linters:
  fast: true
  disable-all: true
  enable:
    - golint
    - unconvert
    - dupl
    - goconst
    - lll
  presets:
    - bugs
    - unused
    - format
    - complexity
    - performance

issues:
  max-per-linter: 0
  max-same-issues: 0
