project_name: nimona
builds:
  - main: cmd/nimona/main.go
    binary: nimona
    env:
      - GO111MODULE=on
    flags: 
      - -a
      - -mod=vendor
      - -tags=releaser
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.ShortCommit}} -X main.Date={{.Date}}
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
      - 386
    goarm:
      - 6
      - 7
archive:
  name_template: '{{ .ProjectName }}-{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
before:
  hooks:
    - make cleanup
snapshot:
  name_template: dev-{{.ShortCommit}}
release:
  draft: true
