env:
  - 'VERSION={{ if index .Env "GORELEASER_NIGHTLY" }}nightly{{ else }}{{ .Version }}{{ end }}'
builds:
  - binary: provider
    main: ./cmd/provider/main.go
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Env.VERSION }} -X main.commit={{ .Commit }}"
    goos:
      - "darwin"
      - "freebsd"
      - "linux"
    goarch:
      - "amd64"
      - "386"
      - "arm"
      - "arm64"
    goarm:
      - "6"
      - "7"

universal_binaries:
  - replace: false

snapshot:
  name_template: "{{ .Tag }}-dev"

changelog:
  skip: true

release:
  skip_upload: true
  disable: true

source:
  enabled: false

dockers:
  - image_templates:
      - "ghcr.io/nimona/nimona:{{ .Env.VERSION }}-amd64"
    dockerfile: dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/nimona/nimona:{{ .Env.VERSION }}-386"
    dockerfile: dockerfile
    use: buildx
    goos: linux
    goarch: "386"
    build_flag_templates:
      - "--platform=linux/386"
  - image_templates:
      - "ghcr.io/nimona/nimona:{{ .Env.VERSION }}-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
  - image_templates:
      - "ghcr.io/nimona/nimona:{{ .Env.VERSION }}-armv6"
    use: buildx
    goos: linux
    goarch: arm
    goarm: "6"
    dockerfile: dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v6"
  - image_templates:
      - "ghcr.io/nimona/nimona:{{ .Env.VERSION }}-armv7"
    use: buildx
    goos: linux
    goarch: arm
    goarm: "7"
    dockerfile: dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v7"

docker_manifests:
  - name_template: ghcr.io/nimona/nimona:{{ .Env.VERSION }}
    image_templates:
      - ghcr.io/nimona/nimona:{{ .Env.VERSION }}-amd64
      - ghcr.io/nimona/nimona:{{ .Env.VERSION }}-386
      - ghcr.io/nimona/nimona:{{ .Env.VERSION }}-arm64
      - ghcr.io/nimona/nimona:{{ .Env.VERSION }}-armv6
      - ghcr.io/nimona/nimona:{{ .Env.VERSION }}-armv7
