// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package nimona

import (
	"bytes"
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	zero "github.com/vikyd/zero"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = bytes.Compare
var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = zero.IsZeroVal

func (t *StreamRequest) MarshalCBORBytes() ([]byte, error) {
	w := bytes.NewBuffer(nil)
	err := t.MarshalCBOR(w)
	if err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}

func (t *StreamRequest) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{162}); err != nil {
		return err
	}

	// t.Type (string) (string)
	if len("$type") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"$type\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("$type"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("$type")); err != nil {
		return err
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("core/stream/request"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("core/stream/request")); err != nil {
		return err
	}

	// t.RootID (nimona.DocumentID) (struct)
	if len("RootID") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"RootID\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("RootID"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("RootID")); err != nil {
		return err
	}

	if err := t.RootID.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *StreamRequest) UnmarshalCBORBytes(b []byte) (err error) {
	*t = StreamRequest{}
	return t.UnmarshalCBOR(bytes.NewReader(b))
}

func (t *StreamRequest) UnmarshalCBOR(r io.Reader) (err error) {
	if t == nil {
		*t = StreamRequest{}
	}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("StreamRequest: map struct too large (%d)", extra)
	}

	var name string
	n := extra

	for i := uint64(0); i < n; i++ {

		{
			sval, err := cbg.ReadString(cr)
			if err != nil {
				return err
			}

			name = string(sval)
		}

		switch name {
		// t.Type (string) (string)
		case "$type":

			{
				sval, err := cbg.ReadString(cr)
				if err != nil {
					return err
				}

				t.Type = string(sval)
			}
			// t.RootID (nimona.DocumentID) (struct)
		case "RootID":

			{

				if err := t.RootID.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.RootID: %w", err)
				}

			}

		default:
			// Field doesn't exist on this type, so ignore it
			cbg.ScanForLinks(r, func(cid.Cid) {})
		}
	}

	return nil
}

func (t *StreamResponse) MarshalCBORBytes() ([]byte, error) {
	w := bytes.NewBuffer(nil)
	err := t.MarshalCBOR(w)
	if err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}

func (t *StreamResponse) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{163}); err != nil {
		return err
	}

	// t.Type (string) (string)
	if len("$type") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"$type\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("$type"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("$type")); err != nil {
		return err
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("core/stream/response"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("core/stream/response")); err != nil {
		return err
	}

	// t.RootDocumentID (nimona.DocumentID) (struct)
	if len("RootDocumentID") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"RootDocumentID\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("RootDocumentID"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("RootDocumentID")); err != nil {
		return err
	}

	if err := t.RootDocumentID.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.PatchDocumentIDs ([]nimona.DocumentID) (slice)
	if len("PatchDocumentIDs") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"PatchDocumentIDs\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("PatchDocumentIDs"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("PatchDocumentIDs")); err != nil {
		return err
	}

	if len(t.PatchDocumentIDs) > cbg.MaxLength {
		return xerrors.Errorf("Slice value in field t.PatchDocumentIDs was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.PatchDocumentIDs))); err != nil {
		return err
	}
	for _, v := range t.PatchDocumentIDs {
		if err := v.MarshalCBOR(cw); err != nil {
			return err
		}
	}
	return nil
}

func (t *StreamResponse) UnmarshalCBORBytes(b []byte) (err error) {
	*t = StreamResponse{}
	return t.UnmarshalCBOR(bytes.NewReader(b))
}

func (t *StreamResponse) UnmarshalCBOR(r io.Reader) (err error) {
	if t == nil {
		*t = StreamResponse{}
	}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("StreamResponse: map struct too large (%d)", extra)
	}

	var name string
	n := extra

	for i := uint64(0); i < n; i++ {

		{
			sval, err := cbg.ReadString(cr)
			if err != nil {
				return err
			}

			name = string(sval)
		}

		switch name {
		// t.Type (string) (string)
		case "$type":

			{
				sval, err := cbg.ReadString(cr)
				if err != nil {
					return err
				}

				t.Type = string(sval)
			}
			// t.RootDocumentID (nimona.DocumentID) (struct)
		case "RootDocumentID":

			{

				if err := t.RootDocumentID.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.RootDocumentID: %w", err)
				}

			}
			// t.PatchDocumentIDs ([]nimona.DocumentID) (slice)
		case "PatchDocumentIDs":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > cbg.MaxLength {
				return fmt.Errorf("t.PatchDocumentIDs: array too large (%d)", extra)
			}

			if maj != cbg.MajArray {
				return fmt.Errorf("expected cbor array")
			}

			if extra > 0 {
				t.PatchDocumentIDs = make([]DocumentID, extra)
			}

			for i := 0; i < int(extra); i++ {

				var v DocumentID
				if err := v.UnmarshalCBOR(cr); err != nil {
					return err
				}

				t.PatchDocumentIDs[i] = v
			}

		default:
			// Field doesn't exist on this type, so ignore it
			cbg.ScanForLinks(r, func(cid.Cid) {})
		}
	}

	return nil
}
