// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package nimona

import (
	"bytes"
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	zero "github.com/vikyd/zero"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = bytes.Compare
var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = zero.IsZeroVal

func (t *DocumentGraphRequest) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{162}); err != nil {
		return err
	}

	// t.Type (string) (string)
	if len("$type") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"$type\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("$type"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("$type")); err != nil {
		return err
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("core/document/graph.request"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("core/document/graph.request")); err != nil {
		return err
	}

	// t.RootDocumentID (nimona.DocumentID) (struct)
	if len("rootDocument") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"rootDocument\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("rootDocument"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("rootDocument")); err != nil {
		return err
	}

	if err := t.RootDocumentID.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *DocumentGraphRequest) UnmarshalCBOR(r io.Reader) (err error) {
	if t == nil {
		*t = DocumentGraphRequest{}
	}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("DocumentGraphRequest: map struct too large (%d)", extra)
	}

	var name string
	n := extra

	for i := uint64(0); i < n; i++ {

		{
			sval, err := cbg.ReadString(cr)
			if err != nil {
				return err
			}

			name = string(sval)
		}

		switch name {
		// t.Type (string) (string)
		case "$type":

			{
				sval, err := cbg.ReadString(cr)
				if err != nil {
					return err
				}

				t.Type = string(sval)
			}
			// t.RootDocumentID (nimona.DocumentID) (struct)
		case "rootDocument":

			{

				if err := t.RootDocumentID.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.RootDocumentID: %w", err)
				}

			}

		default:
			// Field doesn't exist on this type, so ignore it
			cbg.ScanForLinks(r, func(cid.Cid) {})
		}
	}

	return nil
}

func (t *DocumentGraphResponse) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{163}); err != nil {
		return err
	}

	// t.Type (string) (string)
	if len("$type") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"$type\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("$type"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("$type")); err != nil {
		return err
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("core/document/graph.response"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("core/document/graph.response")); err != nil {
		return err
	}

	// t.RootDocumentID (nimona.DocumentID) (struct)
	if len("rootDocumentID") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"rootDocumentID\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("rootDocumentID"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("rootDocumentID")); err != nil {
		return err
	}

	if err := t.RootDocumentID.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.PatchDocumentIDs ([]nimona.DocumentID) (slice)
	if len("patchDocumentIDs") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"patchDocumentIDs\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("patchDocumentIDs"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("patchDocumentIDs")); err != nil {
		return err
	}

	if len(t.PatchDocumentIDs) > cbg.MaxLength {
		return xerrors.Errorf("Slice value in field t.PatchDocumentIDs was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.PatchDocumentIDs))); err != nil {
		return err
	}
	for _, v := range t.PatchDocumentIDs {
		if err := v.MarshalCBOR(cw); err != nil {
			return err
		}
	}
	return nil
}

func (t *DocumentGraphResponse) UnmarshalCBOR(r io.Reader) (err error) {
	if t == nil {
		*t = DocumentGraphResponse{}
	}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("DocumentGraphResponse: map struct too large (%d)", extra)
	}

	var name string
	n := extra

	for i := uint64(0); i < n; i++ {

		{
			sval, err := cbg.ReadString(cr)
			if err != nil {
				return err
			}

			name = string(sval)
		}

		switch name {
		// t.Type (string) (string)
		case "$type":

			{
				sval, err := cbg.ReadString(cr)
				if err != nil {
					return err
				}

				t.Type = string(sval)
			}
			// t.RootDocumentID (nimona.DocumentID) (struct)
		case "rootDocumentID":

			{

				if err := t.RootDocumentID.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.RootDocumentID: %w", err)
				}

			}
			// t.PatchDocumentIDs ([]nimona.DocumentID) (slice)
		case "patchDocumentIDs":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > cbg.MaxLength {
				return fmt.Errorf("t.PatchDocumentIDs: array too large (%d)", extra)
			}

			if maj != cbg.MajArray {
				return fmt.Errorf("expected cbor array")
			}

			if extra > 0 {
				t.PatchDocumentIDs = make([]DocumentID, extra)
			}

			for i := 0; i < int(extra); i++ {

				var v DocumentID
				if err := v.UnmarshalCBOR(cr); err != nil {
					return err
				}

				t.PatchDocumentIDs[i] = v
			}

		default:
			// Field doesn't exist on this type, so ignore it
			cbg.ScanForLinks(r, func(cid.Cid) {})
		}
	}

	return nil
}
