// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package nimona

import (
	"bytes"
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = bytes.Compare
var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *PeerAddr) MarshalCBORBytes() ([]byte, error) {
	w := bytes.NewBuffer(nil)
	err := t.MarshalCBOR(w)
	if err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}

func (t *PeerAddr) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{164}); err != nil {
		return err
	}

	// t._ (string) (string)
	if len("$type") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"$type\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("$type"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("$type")); err != nil {
		return err
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("core/node.address"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("core/node.address")); err != nil {
		return err
	}

	// t.Address (string) (string)
	if len("address") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"address\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("address"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("address")); err != nil {
		return err
	}

	if len(t.Address) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.Address was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Address))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.Address)); err != nil {
		return err
	}

	// t.Network (string) (string)
	if len("network") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"network\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("network"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("network")); err != nil {
		return err
	}

	if len(t.Network) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.Network was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Network))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.Network)); err != nil {
		return err
	}

	// t.PublicKey ([]uint8) (slice)
	if len("publicKey") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"publicKey\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("publicKey"))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string("publicKey")); err != nil {
		return err
	}

	if len(t.PublicKey) > cbg.ByteArrayMaxLen {
		return xerrors.Errorf("Byte array in field t.PublicKey was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.PublicKey))); err != nil {
		return err
	}

	if _, err := cw.Write(t.PublicKey[:]); err != nil {
		return err
	}
	return nil
}

func (t *PeerAddr) UnmarshalCBORBytes(b []byte) (err error) {
	return t.UnmarshalCBOR(bytes.NewReader(b))
}

func (t *PeerAddr) UnmarshalCBOR(r io.Reader) (err error) {
	*t = PeerAddr{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("PeerAddr: map struct too large (%d)", extra)
	}

	var name string
	n := extra

	for i := uint64(0); i < n; i++ {

		{
			sval, err := cbg.ReadString(cr)
			if err != nil {
				return err
			}

			name = string(sval)
		}

		switch name {
		// t._ (string) (string) - ignored

		// t.Address (string) (string)
		case "address":

			{
				sval, err := cbg.ReadString(cr)
				if err != nil {
					return err
				}

				t.Address = string(sval)
			}
			// t.Network (string) (string)
		case "network":

			{
				sval, err := cbg.ReadString(cr)
				if err != nil {
					return err
				}

				t.Network = string(sval)
			}
			// t.PublicKey ([]uint8) (slice)
		case "publicKey":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > cbg.ByteArrayMaxLen {
				return fmt.Errorf("t.PublicKey: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.PublicKey = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.PublicKey[:]); err != nil {
				return err
			}

		default:
			// Field doesn't exist on this type, so ignore it
			cbg.ScanForLinks(r, func(cid.Cid) {})
		}
	}

	return nil
}
