// Code generated by nimona.io/tools/objectify. DO NOT EDIT.

// +build !generate

package dht

import (
	"github.com/mitchellh/mapstructure"
	"nimona.io/pkg/object"
)

const (
	ProviderResponseType = "nimona.io/dht/provider.response"
)

// ToObject returns a f12n object
func (s ProviderResponse) ToObject() *object.Object {
	o := object.New()
	o.SetType(ProviderResponseType)
	if s.RequestID != "" {
		o.SetRaw("requestID", s.RequestID)
	}
	if len(s.Providers) > 0 {
		o.SetRaw("providers", s.Providers)
	}
	if len(s.ClosestPeers) > 0 {
		o.SetRaw("closestPeers", s.ClosestPeers)
	}
	return o
}

func anythingToAnythingForProviderResponse(
	from interface{},
	to interface{},
) error {
	config := &mapstructure.DecoderConfig{
		Result:  to,
		TagName: "json",
	}

	decoder, err := mapstructure.NewDecoder(config)
	if err != nil {
		return err
	}

	if err := decoder.Decode(from); err != nil {
		return err
	}

	return nil
}

// FromObject populates the struct from a f12n object
func (s *ProviderResponse) FromObject(o *object.Object) error {
	atoa := anythingToAnythingForProviderResponse
	if err := atoa(o.GetRaw("requestID"), &s.RequestID); err != nil {
		return err
	}
	if err := atoa(o.GetRaw("providers"), &s.Providers); err != nil {
		return err
	}
	if err := atoa(o.GetRaw("closestPeers"), &s.ClosestPeers); err != nil {
		return err
	}

	if ao, ok := interface{}(s).(interface{ afterFromObject() }); ok {
		ao.afterFromObject()
	}

	return nil
}

// GetType returns the object's type
func (s ProviderResponse) GetType() string {
	return ProviderResponseType
}
