// Code generated by nimona.io/tools/codegen. DO NOT EDIT.

package peer

import (
	"errors"

	crypto "nimona.io/pkg/crypto"
	immutable "nimona.io/pkg/immutable"
	object "nimona.io/pkg/object"
)

type (
	Certificate struct {
		raw        object.Object
		Stream     object.Hash
		Parents    []object.Hash
		Owners     []crypto.PublicKey
		Policy     object.Policy
		Signatures []object.Signature
		Subject    crypto.PublicKey
		Created    string
		Expires    string
	}
)

func (e Certificate) GetType() string {
	return "nimona.io/peer.Certificate"
}

func (e Certificate) GetSchema() *object.SchemaObject {
	return &object.SchemaObject{
		Properties: []*object.SchemaProperty{
			&object.SchemaProperty{
				Name:       "subject",
				Type:       "nimona.io/crypto.PublicKey",
				Hint:       "s",
				IsRepeated: false,
				IsOptional: false,
			},
			&object.SchemaProperty{
				Name:       "created",
				Type:       "string",
				Hint:       "s",
				IsRepeated: false,
				IsOptional: false,
			},
			&object.SchemaProperty{
				Name:       "expires",
				Type:       "string",
				Hint:       "s",
				IsRepeated: false,
				IsOptional: false,
			},
		},
	}
}

func (e Certificate) ToObject() object.Object {
	o := object.Object{}
	o = o.SetType("nimona.io/peer.Certificate")
	if len(e.Stream) > 0 {
		o = o.SetStream(e.Stream)
	}
	if len(e.Parents) > 0 {
		o = o.SetParents(e.Parents)
	}
	if len(e.Owners) > 0 {
		o = o.SetOwners(e.Owners)
	}
	o = o.AddSignature(e.Signatures...)
	o = o.SetPolicy(e.Policy)
	if e.Subject != "" {
		o = o.Set("subject:s", e.Subject)
	}
	if e.Created != "" {
		o = o.Set("created:s", e.Created)
	}
	if e.Expires != "" {
		o = o.Set("expires:s", e.Expires)
	}
	// if schema := e.GetSchema(); schema != nil {
	// 	m["_schema:o"] = schema.ToObject().ToMap()
	// }
	return o
}

func (e *Certificate) FromObject(o object.Object) error {
	data, ok := o.Raw().Value("data:o").(immutable.Map)
	if !ok {
		return errors.New("missing data")
	}
	e.raw = object.Object{}
	e.raw = e.raw.SetType(o.GetType())
	e.Stream = o.GetStream()
	e.Parents = o.GetParents()
	e.Owners = o.GetOwners()
	e.Signatures = o.GetSignatures()
	e.Policy = o.GetPolicy()
	if v := data.Value("subject:s"); v != nil {
		e.Subject = crypto.PublicKey(v.PrimitiveHinted().(string))
	}
	if v := data.Value("created:s"); v != nil {
		e.Created = string(v.PrimitiveHinted().(string))
	}
	if v := data.Value("expires:s"); v != nil {
		e.Expires = string(v.PrimitiveHinted().(string))
	}
	return nil
}
