// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package peer

import "sync"

type (
	// OnAddressesUpdatedBoolSyncMap -
	OnAddressesUpdatedBoolSyncMap struct {
		m sync.Map
	}
)

// NewOnAddressesUpdatedBoolSyncMap constructs a new SyncMap
func NewOnAddressesUpdatedBoolSyncMap() *OnAddressesUpdatedBoolSyncMap {
	return &OnAddressesUpdatedBoolSyncMap{}
}

// Put -
func (m *OnAddressesUpdatedBoolSyncMap) Put(k OnAddressesUpdated, v *bool) {
	m.m.Store(k, v)
}

// Get -
func (m *OnAddressesUpdatedBoolSyncMap) Get(k OnAddressesUpdated) (*bool, bool) {
	i, ok := m.m.Load(k)
	if !ok {
		return nil, false
	}

	v, ok := i.(*bool)
	if !ok {
		return nil, false
	}

	return v, true
}

// Delete -
func (m *OnAddressesUpdatedBoolSyncMap) Delete(k OnAddressesUpdated) {
	m.m.Delete(k)
}

// Range -
func (m *OnAddressesUpdatedBoolSyncMap) Range(i func(k OnAddressesUpdated, v *bool) bool) {
	m.m.Range(func(k, v interface{}) bool {
		return i(k.(OnAddressesUpdated), v.(*bool))
	})
}
