// Code generated by nimona.io/tools/codegen. DO NOT EDIT.

package hyperspace

import (
	object "nimona.io/pkg/object"
	peer "nimona.io/pkg/peer"
)

const AnnouncementType = "nimona.io/hyperspace.Announcement"

type Announcement struct {
	Metadata         object.Metadata      `nimona:"@metadata:m,type=nimona.io/hyperspace.Announcement"`
	Version          int64                `nimona:"version:i"`
	ConnectionInfo   *peer.ConnectionInfo `nimona:"connectionInfo:m"`
	PeerVector       []uint64             `nimona:"peerVector:au"`
	PeerCapabilities []string             `nimona:"peerCapabilities:as"`
}

const LookupRequestType = "nimona.io/hyperspace.LookupRequest"

type LookupRequest struct {
	Metadata            object.Metadata `nimona:"@metadata:m,type=nimona.io/hyperspace.LookupRequest"`
	Nonce               string          `nimona:"nonce:s"`
	QueryVector         []uint64        `nimona:"queryVector:au"`
	RequireCapabilities []string        `nimona:"requireCapabilities:as"`
}

const LookupResponseType = "nimona.io/hyperspace.LookupResponse"

type LookupResponse struct {
	Metadata      object.Metadata `nimona:"@metadata:m,type=nimona.io/hyperspace.LookupResponse"`
	Nonce         string          `nimona:"nonce:s"`
	QueryVector   []uint64        `nimona:"queryVector:au"`
	Announcements []*Announcement `nimona:"announcements:am"`
}
