// Code generated by nimona.io/tools/codegen. DO NOT EDIT.

package hyperspace

import (
	object "nimona.io/pkg/object"
	peer "nimona.io/pkg/peer"
)

type (
	Announcement struct {
		Metadata         object.Metadata      `nimona:"@metadata:m"`
		Version          int64                `nimona:"version:i"`
		ConnectionInfo   *peer.ConnectionInfo `nimona:"connectionInfo:m"`
		PeerVector       []uint64             `nimona:"peerVector:au"`
		PeerCapabilities []string             `nimona:"peerCapabilities:as"`
	}
	LookupRequest struct {
		Metadata            object.Metadata `nimona:"@metadata:m"`
		Nonce               string          `nimona:"nonce:s"`
		QueryVector         []uint64        `nimona:"queryVector:au"`
		RequireCapabilities []string        `nimona:"requireCapabilities:as"`
	}
	LookupResponse struct {
		Metadata      object.Metadata `nimona:"@metadata:m"`
		Nonce         string          `nimona:"nonce:s"`
		QueryVector   []uint64        `nimona:"queryVector:au"`
		Announcements []*Announcement `nimona:"announcements:am"`
	}
)

func (e *Announcement) Type() string {
	return "nimona.io/hyperspace.Announcement"
}

func (e *Announcement) MarshalObject() (*object.Object, error) {
	o, err := object.Marshal(e)
	if err != nil {
		return nil, err
	}
	o.Type = "nimona.io/hyperspace.Announcement"
	return o, nil
}

func (e *Announcement) UnmarshalObject(o *object.Object) error {
	return object.Unmarshal(o, e)
}

func (e *LookupRequest) Type() string {
	return "nimona.io/hyperspace.LookupRequest"
}

func (e *LookupRequest) MarshalObject() (*object.Object, error) {
	o, err := object.Marshal(e)
	if err != nil {
		return nil, err
	}
	o.Type = "nimona.io/hyperspace.LookupRequest"
	return o, nil
}

func (e *LookupRequest) UnmarshalObject(o *object.Object) error {
	return object.Unmarshal(o, e)
}

func (e *LookupResponse) Type() string {
	return "nimona.io/hyperspace.LookupResponse"
}

func (e *LookupResponse) MarshalObject() (*object.Object, error) {
	o, err := object.Marshal(e)
	if err != nil {
		return nil, err
	}
	o.Type = "nimona.io/hyperspace.LookupResponse"
	return o, nil
}

func (e *LookupResponse) UnmarshalObject(o *object.Object) error {
	return object.Unmarshal(o, e)
}
