// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/geoah/genny

package network

import (
	"sync"
)

type (
	outboxes string // nolint
	// OutboxesMap -
	OutboxesMap struct {
		m sync.Map
	}
)

// NewOutboxesMap constructs a new SyncMap
func NewOutboxesMap() *OutboxesMap {
	return &OutboxesMap{}
}

// GetOrPut -
func (m *OutboxesMap) GetOrPut(k string, v *outbox) (*outbox, bool) {
	nv, ok := m.m.LoadOrStore(k, v)
	return nv.(*outbox), ok
}

// Put -
func (m *OutboxesMap) Put(k string, v *outbox) {
	m.m.Store(k, v)
}

// Get -
func (m *OutboxesMap) Get(k string) (*outbox, bool) {
	i, ok := m.m.Load(k)
	if !ok {
		return nil, false
	}

	v, ok := i.(*outbox)
	if !ok {
		return nil, false
	}

	return v, true
}

// Delete -
func (m *OutboxesMap) Delete(k string) {
	m.m.Delete(k)
}

// Range -
func (m *OutboxesMap) Range(i func(k string, v *outbox) bool) {
	m.m.Range(func(k, v interface{}) bool {
		return i(k.(string), v.(*outbox))
	})
}

// ListKeys -
func (m *OutboxesMap) ListKeys() []string {
	vs := []string{}
	m.m.Range(func(k, v interface{}) bool {
		vs = append(vs, k.(string))
		return true
	})
	return vs
}

// ListValues -
func (m *OutboxesMap) ListValues() []*outbox {
	vs := []*outbox{}
	m.m.Range(func(k, v interface{}) bool {
		vs = append(vs, v.(*outbox))
		return true
	})
	return vs
}
