// Code generated by nimona.io/tools/objectify. DO NOT EDIT.

// +build !generate

package dag

import (
	"github.com/mitchellh/mapstructure"
	"nimona.io/pkg/crypto"
	"nimona.io/pkg/object"
)

const (
	ObjectGraphRequestType = "/object-graph-request"
)

// ToObject returns a f12n object
func (s ObjectGraphRequest) ToObject() *object.Object {
	o := object.New()
	o.SetType(ObjectGraphRequestType)
	if len(s.Selector) > 0 {
		o.SetRaw("selector", s.Selector)
	}
	if s.Signer != nil {
		o.SetRaw("@signer", s.Signer)
	}
	if s.Signature != nil {
		o.SetRaw("@signature", s.Signature)
	}
	return o
}

func anythingToAnythingForObjectGraphRequest(
	from interface{},
	to interface{},
) error {
	config := &mapstructure.DecoderConfig{
		Result:  to,
		TagName: "json",
	}

	decoder, err := mapstructure.NewDecoder(config)
	if err != nil {
		return err
	}

	if err := decoder.Decode(from); err != nil {
		return err
	}

	return nil
}

// FromObject populates the struct from a f12n object
func (s *ObjectGraphRequest) FromObject(o *object.Object) error {
	atoa := anythingToAnythingForObjectGraphRequest
	if err := atoa(o.GetRaw("selector"), &s.Selector); err != nil {
		return err
	}
	if v, ok := o.GetRaw("@signer").(*crypto.Key); ok {
		s.Signer = v
	} else if v, ok := o.GetRaw("@signer").(map[string]interface{}); ok {
		s.Signer = &crypto.Key{}
		o := &object.Object{}
		if err := o.FromMap(v); err != nil {
			return err
		}
		s.Signer.FromObject(o)
	}
	if v, ok := o.GetRaw("@signature").(*crypto.Signature); ok {
		s.Signature = v
	} else if v, ok := o.GetRaw("@signature").(map[string]interface{}); ok {
		s.Signature = &crypto.Signature{}
		o := &object.Object{}
		if err := o.FromMap(v); err != nil {
			return err
		}
		s.Signature.FromObject(o)
	}

	return nil
}

// GetType returns the object's type
func (s ObjectGraphRequest) GetType() string {
	return ObjectGraphRequestType
}
