// Code generated by nimona.io/tools/codegen. DO NOT EDIT.

package exchange

import (
	json "encoding/json"

	"nimona.io/pkg/crypto"
	object "nimona.io/pkg/object"
)

type (
	ObjectRequest struct {
		ObjectHash *object.Hash        `json:"objectHash:o,omitempty"`
		Signature  *crypto.Signature   `json:"@signature:o,omitempty"`
		Authors    []*crypto.PublicKey `json:"@authors:ao,omitempty"`
	}
	ObjectForward struct {
		Recipient string              `json:"recipient:s,omitempty"`
		FwObject  *object.Object      `json:"fwObject:o,omitempty"`
		Signature *crypto.Signature   `json:"@signature:o,omitempty"`
		Authors   []*crypto.PublicKey `json:"@authors:ao,omitempty"`
	}
)

func (e *ObjectRequest) GetType() string {
	return "nimona.io/exchange.ObjectRequest"
}

func (e *ObjectRequest) ToObject() object.Object {
	m := map[string]interface{}{
		"@ctx:s": "nimona.io/exchange.ObjectRequest",
	}
	b, _ := json.Marshal(e)
	json.Unmarshal(b, &m)
	return object.Object(m)
}

func (e *ObjectRequest) FromObject(o object.Object) error {
	b, _ := json.Marshal(map[string]interface{}(o))
	return json.Unmarshal(b, e)
}

func (e *ObjectForward) GetType() string {
	return "nimona.io/exchange.ObjectForward"
}

func (e *ObjectForward) ToObject() object.Object {
	m := map[string]interface{}{
		"@ctx:s": "nimona.io/exchange.ObjectForward",
	}
	b, _ := json.Marshal(e)
	json.Unmarshal(b, &m)
	return object.Object(m)
}

func (e *ObjectForward) FromObject(o object.Object) error {
	b, _ := json.Marshal(map[string]interface{}(o))
	return json.Unmarshal(b, e)
}
