// Code generated by mockery v1.0.0. DO NOT EDIT.

package exchange

import context "nimona.io/internal/context"
import mock "github.com/stretchr/testify/mock"
import object "nimona.io/pkg/object"

// MockExchange is an autogenerated mock type for the Exchange type
type MockExchange struct {
	mock.Mock
}

// Handle provides a mock function with given fields: contentTypeGlob, handler
func (_m *MockExchange) Handle(contentTypeGlob string, handler func(*Envelope) error) (func(), error) {
	ret := _m.Called(contentTypeGlob, handler)

	var r0 func()
	if rf, ok := ret.Get(0).(func(string, func(*Envelope) error) func()); ok {
		r0 = rf(contentTypeGlob, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, func(*Envelope) error) error); ok {
		r1 = rf(contentTypeGlob, handler)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Request provides a mock function with given fields: ctx, objectHash, address, options
func (_m *MockExchange) Request(ctx context.Context, objectHash string, address string, options ...Option) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, objectHash, address)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...Option) error); ok {
		r0 = rf(ctx, objectHash, address, options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Send provides a mock function with given fields: ctx, _a1, address, options
func (_m *MockExchange) Send(ctx context.Context, _a1 object.Object, address string, options ...Option) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, _a1, address)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, object.Object, string, ...Option) error); ok {
		r0 = rf(ctx, _a1, address, options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
