// Code generated by nimona.io/tools/objectify. DO NOT EDIT.

// +build !generate

package exchange

import (
	"encoding/json"

	"nimona.io/pkg/object"
)

const (
	ObjectRequestType = "/object-request"
)

// ToObject returns a f12n object
func (s ObjectRequest) ToObject() object.Object {
	m := map[string]interface{}{
		"@ctx:s": ObjectRequestType,
	}
	b, _ := json.Marshal(s)
	json.Unmarshal(b, &m)
	return object.Object(m)
}

// FromObject populates the struct from a f12n object
func (s *ObjectRequest) FromObject(o object.Object) error {
	b, _ := json.Marshal(map[string]interface{}(o))
	return json.Unmarshal(b, s)
}

// GetType returns the object's type
func (s ObjectRequest) GetType() string {
	return ObjectRequestType
}
