// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/geoah/genny

package localpeer

import (
	"sync"

	"nimona.io/pkg/object"
)

type (
	// ObjectCertificateSyncList -
	ObjectCertificateSyncList struct {
		m sync.Map
	}
)

// Put -
func (m *ObjectCertificateSyncList) Put(k *object.Certificate) {
	m.m.Store(k, true)
}

// Exists -
func (m *ObjectCertificateSyncList) Exists(k *object.Certificate) bool {
	_, ok := m.m.Load(k)
	return ok
}

// Delete -
func (m *ObjectCertificateSyncList) Delete(k *object.Certificate) {
	m.m.Delete(k)
}

// Range -
func (m *ObjectCertificateSyncList) Range(i func(k *object.Certificate) bool) {
	m.m.Range(func(k, v interface{}) bool {
		return i(k.(*object.Certificate))
	})
}

// List -
func (m *ObjectCertificateSyncList) List() []*object.Certificate {
	r := []*object.Certificate{}
	m.m.Range(func(k, v interface{}) bool {
		r = append(r, k.(*object.Certificate))
		return true
	})
	return r
}
