// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/geoah/genny

package localpeer

import (
	"sync"

	"nimona.io/pkg/object"
)

type (
	// ObjectHashSyncList -
	ObjectHashSyncList struct {
		m sync.Map
	}
)

// Put -
func (m *ObjectHashSyncList) Put(k object.Hash) {
	m.m.Store(k, true)
}

// Exists -
func (m *ObjectHashSyncList) Exists(k object.Hash) bool {
	_, ok := m.m.Load(k)
	return ok
}

// Delete -
func (m *ObjectHashSyncList) Delete(k object.Hash) {
	m.m.Delete(k)
}

// Range -
func (m *ObjectHashSyncList) Range(i func(k object.Hash) bool) {
	m.m.Range(func(k, v interface{}) bool {
		return i(k.(object.Hash))
	})
}

// List -
func (m *ObjectHashSyncList) List() []object.Hash {
	r := []object.Hash{}
	m.m.Range(func(k, v interface{}) bool {
		r = append(r, k.(object.Hash))
		return true
	})
	return r
}
