apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: nimona-proxy
          image: nimona/nimona-proxy:v0.3.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
            - containerPort: 443
              protocol: TCP
              name: https
          env:
            - name: BIND_ADDRESS
              value: 0.0.0.0:443
            - name: TARGETS
              value: "andromeda.bootstrap.nimona.io=andromeda.bootstrap.default.svc.cluster.local:443,\
                borealis.bootstrap.nimona.io=borealis.bootstrap.default.svc.cluster.local:443,\
                cassiopeia.bootstrap.nimona.io=cassiopeia.bootstrap.default.svc.cluster.local:443,\
                draco.bootstrap.nimona.io=draco.bootstrap.default.svc.cluster.local:443,\
                eridanus.bootstrap.nimona.io=eridanus.bootstrap.default.svc.cluster.local:443,\
                fornax.bootstrap.nimona.io=fornax.bootstrap.default.svc.cluster.local:443,\
                gemini.bootstrap.nimona.io=gemini.bootstrap.default.svc.cluster.local:443,\
                hydra.bootstrap.nimona.io=hydra.bootstrap.default.svc.cluster.local:443,\
                indus.bootstrap.nimona.io=indus.bootstrap.default.svc.cluster.local:443,\
                lacerta.bootstrap.nimona.io=lacerta.bootstrap.default.svc.cluster.local:443,\
                mensa.bootstrap.nimona.io=mensa.bootstrap.default.svc.cluster.local:443,\
                norma.bootstrap.nimona.io=norma.bootstrap.default.svc.cluster.local:443,\
                orion.bootstrap.nimona.io=orion.bootstrap.default.svc.cluster.local:443,\
                pyxis.bootstrap.nimona.io=pyxis.bootstrap.default.svc.cluster.local:443,\
                stats.bootstrap.nimona.io=stats.bootstrap.default.svc.cluster.local:443"
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: http
  - port: 443
    protocol: TCP
    name: https
    targetPort: https
  selector:
    app: proxy
