apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: nimona-proxy
          image: nimona/nimona-proxy:v0.3.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
            - containerPort: 443
              protocol: TCP
              name: https
          env:
            - name: BIND_ADDRESS
              value: 0.0.0.0:443
            - name: TARGETS
              value: andromeda.bootstrap.nimona.io=andromeda.bootstrap.default.svc.cluster.local:443
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: http
  - port: 443
    protocol: TCP
    name: https
    targetPort: https
  selector:
    app: proxy
