// Code generated by nimona.io/tools/objectify. DO NOT EDIT.

// +build !generate

package peer

import (
	"nimona.io/pkg/crypto"
	"nimona.io/pkg/object"
)

const (
	PeerInfoRequestType = "/peer.request"
)

// ToObject returns a f12n object
func (s PeerInfoRequest) ToObject() *object.Object {
	o := object.New()
	o.SetType(PeerInfoRequestType)
	if s.AuthorityKeyHash != "" {
		o.SetRaw("authority", s.AuthorityKeyHash)
	}
	if s.SignerKeyHash != "" {
		o.SetRaw("signer", s.SignerKeyHash)
	}
	if len(s.Protocols) > 0 {
		o.SetRaw("protocols", s.Protocols)
	}
	if len(s.ContentIDs) > 0 {
		o.SetRaw("contentIDs", s.ContentIDs)
	}
	if len(s.ContentTypes) > 0 {
		o.SetRaw("contentTypes", s.ContentTypes)
	}
	if s.RequesterAuthorityKey != nil {
		o.SetRaw("@authority", s.RequesterAuthorityKey)
	}
	if s.RequesterSignerKey != nil {
		o.SetRaw("@signer", s.RequesterSignerKey)
	}
	if s.RequestSignature != nil {
		o.SetRaw("@signature", s.RequestSignature)
	}
	return o
}

// FromObject populates the struct from a f12n object
func (s *PeerInfoRequest) FromObject(o *object.Object) error {
	if v, ok := o.GetRaw("authority").(string); ok {
		s.AuthorityKeyHash = v
	}
	if v, ok := o.GetRaw("signer").(string); ok {
		s.SignerKeyHash = v
	}
	if ss, ok := o.GetRaw("protocols").([]string); ok {
		s.Protocols = ss
	} else if ss, ok := o.GetRaw("protocols").([]interface{}); ok {
		s.Protocols = []string{}
		for _, si := range ss {
			if v, ok := si.(string); ok {
				s.Protocols = append(s.Protocols, v)
			}
		}
	}
	if ss, ok := o.GetRaw("contentIDs").([]string); ok {
		s.ContentIDs = ss
	} else if ss, ok := o.GetRaw("contentIDs").([]interface{}); ok {
		s.ContentIDs = []string{}
		for _, si := range ss {
			if v, ok := si.(string); ok {
				s.ContentIDs = append(s.ContentIDs, v)
			}
		}
	}
	if ss, ok := o.GetRaw("contentTypes").([]string); ok {
		s.ContentTypes = ss
	} else if ss, ok := o.GetRaw("contentTypes").([]interface{}); ok {
		s.ContentTypes = []string{}
		for _, si := range ss {
			if v, ok := si.(string); ok {
				s.ContentTypes = append(s.ContentTypes, v)
			}
		}
	}
	if v, ok := o.GetRaw("@authority").(*crypto.Key); ok {
		s.RequesterAuthorityKey = v
	} else if v, ok := o.GetRaw("@authority").(*object.Object); ok {
		s.RequesterAuthorityKey = &crypto.Key{}
		s.RequesterAuthorityKey.FromObject(v)
	}
	if v, ok := o.GetRaw("@signer").(*crypto.Key); ok {
		s.RequesterSignerKey = v
	} else if v, ok := o.GetRaw("@signer").(*object.Object); ok {
		s.RequesterSignerKey = &crypto.Key{}
		s.RequesterSignerKey.FromObject(v)
	}
	if v, ok := o.GetRaw("@signature").(*crypto.Signature); ok {
		s.RequestSignature = v
	} else if v, ok := o.GetRaw("@signature").(*object.Object); ok {
		s.RequestSignature = &crypto.Signature{}
		s.RequestSignature.FromObject(v)
	}
	return nil
}

// GetType returns the object's type
func (s PeerInfoRequest) GetType() string {
	return PeerInfoRequestType
}
