---
- hosts: all
  roles:
    - role: oefenweb.ssh_server
      tags: ["network", "ssh"]
    - role: oefenweb.ufw
      tags: ["network", "ufw"]
    - role: oefenweb.fail2ban
      tags: ["network", "fail2ban"]
    - role: volumes
      tags: ["storage", "volumes"]
    - role: docker
      tags: ["tools", "docker"]
    - role: caddy
      tags: ["tools", "caddy", "http"]
