// Code generated by nimona.io/tools/codegen. DO NOT EDIT.

package fixtures

import (
	object "nimona.io/pkg/object"
)

type (
	CompositeTest struct {
		Metadata                    object.Metadata `nimona:"@metadata:m"`
		CompositeStringTest         *Composite      `nimona:"compositeStringTest:s"`
		CompositeDataTest           *Composite      `nimona:"compositeDataTest:d"`
		RepeatedCompositeStringTest []*Composite    `nimona:"repeatedCompositeStringTest:as"`
		RepeatedCompositeDataTest   []*Composite    `nimona:"repeatedCompositeDataTest:ad"`
	}
	TestPolicy struct {
		Metadata   object.Metadata `nimona:"@metadata:m"`
		Subjects   []string        `nimona:"subjects:as"`
		Resources  []string        `nimona:"resources:as"`
		Conditions []string        `nimona:"conditions:as"`
		Action     string          `nimona:"action:s"`
	}
	TestStream struct {
		Metadata        object.Metadata `nimona:"@metadata:m"`
		Nonce           string          `nimona:"nonce:s"`
		CreatedDateTime string          `nimona:"createdDateTime:s"`
	}
	TestSubscribed struct {
		Metadata object.Metadata `nimona:"@metadata:m"`
		Nonce    string          `nimona:"nonce:s"`
	}
	TestUnsubscribed struct {
		Metadata object.Metadata `nimona:"@metadata:m"`
		Nonce    string          `nimona:"nonce:s"`
	}
	TestRequest struct {
		Metadata  object.Metadata `nimona:"@metadata:m"`
		RequestID string          `nimona:"requestID:s"`
		Foo       string          `nimona:"foo:s"`
	}
	TestResponse struct {
		Metadata  object.Metadata `nimona:"@metadata:m"`
		RequestID string          `nimona:"requestID:s"`
		Foo       string          `nimona:"foo:s"`
	}
	Parent struct {
		Metadata      object.Metadata `nimona:"@metadata:m"`
		Foo           string          `nimona:"foo:s"`
		Child         *Child          `nimona:"child:m"`
		RepeatedChild []*Child        `nimona:"repeatedChild:am"`
	}
	Child struct {
		Metadata object.Metadata `nimona:"@metadata:m"`
		Foo      string          `nimona:"foo:s"`
	}
)

func (e *CompositeTest) Type() string {
	return "compositeTest"
}

func (e *TestPolicy) Type() string {
	return "nimona.io/fixtures.TestPolicy"
}

func (e *TestStream) Type() string {
	return "nimona.io/fixtures.TestStream"
}

func (e *TestSubscribed) Type() string {
	return "nimona.io/fixtures.TestSubscribed"
}

func (e *TestUnsubscribed) Type() string {
	return "nimona.io/fixtures.TestUnsubscribed"
}

func (e *TestRequest) Type() string {
	return "nimona.io/fixtures.TestRequest"
}

func (e *TestResponse) Type() string {
	return "nimona.io/fixtures.TestResponse"
}

func (e *Parent) Type() string {
	return "parent"
}

func (e *Child) Type() string {
	return "child"
}
