// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "nimona.io/pkg/context"
import crypto "nimona.io/pkg/crypto"
import discovery "nimona.io/pkg/discovery"
import mock "github.com/stretchr/testify/mock"
import object "nimona.io/pkg/object"
import peer "nimona.io/pkg/peer"

// Discoverer is an autogenerated mock type for the Discoverer type
type Discoverer struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *Discoverer) Add(_a0 *peer.Peer) {
	_m.Called(_a0)
}

// AddProvider provides a mock function with given fields: provider
func (_m *Discoverer) AddProvider(provider discovery.Provider) error {
	ret := _m.Called(provider)

	var r0 error
	if rf, ok := ret.Get(0).(func(discovery.Provider) error); ok {
		r0 = rf(provider)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByContent provides a mock function with given fields: ctx, contentHash, opts
func (_m *Discoverer) FindByContent(ctx context.Context, contentHash object.Hash, opts ...discovery.Option) ([]crypto.PublicKey, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, contentHash)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []crypto.PublicKey
	if rf, ok := ret.Get(0).(func(context.Context, object.Hash, ...discovery.Option) []crypto.PublicKey); ok {
		r0 = rf(ctx, contentHash, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]crypto.PublicKey)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, object.Hash, ...discovery.Option) error); ok {
		r1 = rf(ctx, contentHash, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByPublicKey provides a mock function with given fields: ctx, key, opts
func (_m *Discoverer) FindByPublicKey(ctx context.Context, key crypto.PublicKey, opts ...discovery.Option) ([]*peer.Peer, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*peer.Peer
	if rf, ok := ret.Get(0).(func(context.Context, crypto.PublicKey, ...discovery.Option) []*peer.Peer); ok {
		r0 = rf(ctx, key, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*peer.Peer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, crypto.PublicKey, ...discovery.Option) error); ok {
		r1 = rf(ctx, key, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
