// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "nimona.io/internal/context"
import crypto "nimona.io/pkg/crypto"
import discovery "nimona.io/pkg/discovery"
import mock "github.com/stretchr/testify/mock"
import peer "nimona.io/pkg/net/peer"

// Discoverer is an autogenerated mock type for the Discoverer type
type Discoverer struct {
	mock.Mock
}

// Add provides a mock function with given fields: v
func (_m *Discoverer) Add(v *peer.PeerInfo) {
	_m.Called(v)
}

// AddProvider provides a mock function with given fields: provider
func (_m *Discoverer) AddProvider(provider discovery.Provider) error {
	ret := _m.Called(provider)

	var r0 error
	if rf, ok := ret.Get(0).(func(discovery.Provider) error); ok {
		r0 = rf(provider)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByContent provides a mock function with given fields: ctx, contentHash, opts
func (_m *Discoverer) FindByContent(ctx context.Context, contentHash string, opts ...discovery.Option) ([]*peer.PeerInfo, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, contentHash)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*peer.PeerInfo
	if rf, ok := ret.Get(0).(func(context.Context, string, ...discovery.Option) []*peer.PeerInfo); ok {
		r0 = rf(ctx, contentHash, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*peer.PeerInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, ...discovery.Option) error); ok {
		r1 = rf(ctx, contentHash, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByFingerprint provides a mock function with given fields: ctx, fingerprint, opts
func (_m *Discoverer) FindByFingerprint(ctx context.Context, fingerprint crypto.Fingerprint, opts ...discovery.Option) ([]*peer.PeerInfo, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, fingerprint)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*peer.PeerInfo
	if rf, ok := ret.Get(0).(func(context.Context, crypto.Fingerprint, ...discovery.Option) []*peer.PeerInfo); ok {
		r0 = rf(ctx, fingerprint, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*peer.PeerInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, crypto.Fingerprint, ...discovery.Option) error); ok {
		r1 = rf(ctx, fingerprint, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
