// Code generated by nimona.io/tools/codegen. DO NOT EDIT.

package main

import (
	blob "nimona.io/pkg/blob"
	object "nimona.io/pkg/object"
)

type (
	File struct {
		Metadata object.Metadata `nimona:"metadata:m,omitempty"`
		Name     string          `nimona:"name:s,omitempty"`
		Blob     *blob.Blob      `nimona:"blob:o,omitempty"`
	}
)

func (e *File) Type() string {
	return "nimona.io/File"
}

func (e File) ToObject() *object.Object {
	o, err := object.Encode(&e)
	if err != nil {
		panic(err)
	}
	return o
}

func (e *File) FromObject(o *object.Object) error {
	return object.Decode(o, e)
}
