// Code generated by nimona.io/tools/codegen. DO NOT EDIT.

package main

import (
	object "nimona.io/pkg/object"
)

type (
	File struct {
		Metadata object.Metadata `nimona:"metadata:m,omitempty"`
		Name     string          `nimona:"name:s,omitempty"`
		Blob     object.Hash     `nimona:"blob:r,omitempty"`
	}
)

func (e *File) Type() string {
	return "nimona.io/File"
}

func (e File) ToObject() *object.Object {
	r := &object.Object{
		Type:     "nimona.io/File",
		Metadata: e.Metadata,
		Data:     map[string]interface{}{},
	}
	r.Data["name:s"] = e.Name
	r.Data["blob:r"] = e.Blob
	return r
}

func (e *File) FromObject(o *object.Object) error {
	return object.Decode(o, e)
}
