// Code generated by nimona.io/tools/codegen. DO NOT EDIT.

package main

import (
	chore "nimona.io/pkg/chore"
	object "nimona.io/pkg/object"
)

const FileType = "nimona.io/File"

type File struct {
	Metadata object.Metadata `nimona:"@metadata:m,type=nimona.io/File"`
	Name     string          `nimona:"name:s"`
	Blob     chore.Hash      `nimona:"blob:s"`
}
