project_name: nimona
builds:
  - id: linux
    main: ./nimona
    binary: nimona
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
    flags:
      - -tags=releaser
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.ShortCommit}} -X main.Date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - 386
  - id: windows_64
    main: ./nimona
    binary: nimona
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -tags=releaser
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.ShortCommit}} -X main.Date={{.Date}} -extldflags '-static'
    goos:
      - windows
    goarch:
      - amd64
  - id: windows_32
    main: ./nimona
    binary: nimona
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - CC=i686-w64-mingw32-gcc
      - CXX=i686-w64-mingw32-g++
    flags:
      - -tags=releaser
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.ShortCommit}} -X main.Date={{.Date}} -extldflags '-static'
    goos:
      - windows
    goarch:
      - 386
  - id: darwin
    main: ./nimona
    binary: nimona
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -tags=releaser
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.ShortCommit}} -X main.Date={{.Date}}
    goos:
      - darwin
    goarch:
      - amd64
archives:
  - name_template: '{{ .ProjectName }}-{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
      }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - binaries:
      - nimona
    goos: linux
    goarch: amd64
    image_templates:
      - "nimona/nimona:{{ .Tag }}"
    dockerfile: nimona/Dockerfile
    skip_push: false
snapshot:
  name_template: dev-{{.ShortCommit}}
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore'
      - '^docs'
