project_name: nimona
builds:
  - main: ./nimona
    binary: nimona
    env:
      - GO111MODULE=on
    flags:
      - -tags=releaser
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.ShortCommit}} -X main.Date={{.Date}}
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
      - 386
    goarm:
      - 6
      - 7
archives:
  - name_template: '{{ .ProjectName }}-{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
      }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - binaries:
      - nimona
    goos: linux
    goarch: amd64
    image_templates:
      - "nimona/nimona:{{ .Tag }}"
      - "nimona/nimona:v{{ .Major }}"
      - "nimona/nimona:v{{ .Major }}.{{ .Minor }}"
    dockerfile: nimona/Dockerfile
    skip_push: false
snapshot:
  name_template: dev-{{.ShortCommit}}
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore'
      - '^docs'
