---
- import_role:
    name: oefenweb.docker

- name: Install python3-pip
  apt:
    name: python3-pip

- name: Install docker python module
  pip:
    name: docker

- name: Create docker network
  docker_network:
    name: "{{ item }}"
  loop: "{{ docker_networks }}"
