---
- name: Create and start cadvisor container
  community.general.docker_container:
    name: cadvisor
    image: "{{ cadvisor_docker_image }}:{{ cadvisor_docker_tag }}"
    pull: yes
    recreate: "{{ cadvisor_docker_tag == 'latest' }}"
    restart_policy: always
    state: started
    container_default_behavior: no_defaults
    privileged: yes
    networks_cli_compatible: yes
    devices:
      - "/dev/kmsg"
    volumes:
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/:/rootfs:ro"
      - "/dev/disk/:/dev/disk:ro"
      - "/sys:/sys:ro"
      - "/var/run:/var/run:ro"
    published_ports:
      - "127.0.0.1:8080:8080"

- name: Configure caddy
  import_role:
    name: metrics_site
  vars:
    metrics_site_name: cadvisor
    metrics_site_host_path: /metrics/cadvisor
    metrics_site_upstream_path: /metrics
    metrics_site_upstream: "127.0.0.1:8080"
    metrics_site_users: "{{ metrics_users }}"
