---
- hosts: all
  roles:
    - role: oefenweb.ssh_server
      tags: ["network", "ssh"]
    - role: oefenweb.ufw
      tags: ["network", "ufw"]
    - role: oefenweb.fail2ban
      tags: ["network", "fail2ban"]
    - role: docker
      tags: ["tools", "docker"]
    - role: caddy
      tags: ["tools", "caddy", "http"]
    - role: node_exporter
      tags: ["services", "metrics", "node_exporter"]
    - role: cadvisor
      tags: ["services", "metrics", "cadvisor"]
    - role: bootstrap
      tags: ["services", "nimona", "bootstrap"]
