---
ssh_server_challenge_response_authentication: false
ssh_server_password_authentication: false
ssh_server_permit_root_login: "no"
ssh_server_pubkey_authentication: true
ssh_server_use_privilege_separation: true
