// Code generated by nimona.io/tools/codegen. DO NOT EDIT.

package object

import (
	chore "nimona.io/pkg/chore"
)

type (
	Request struct {
		Metadata   Metadata   `nimona:"@metadata:m"`
		RequestID  string     `nimona:"requestID:s"`
		ObjectHash chore.Hash `nimona:"objectHash:s"`
	}
	Response struct {
		Metadata  Metadata `nimona:"@metadata:m"`
		RequestID string   `nimona:"requestID:s"`
		Object    *Object  `nimona:"object:m"`
	}
)

func (e *Request) Type() string {
	return "nimona.io/Request"
}

func (e *Response) Type() string {
	return "nimona.io/Response"
}
