name: Release
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out the code
        uses: actions/checkout@v1

      - name: Publish docker container
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u=$DOCKER_USERNAME -p="$DOCKER_PASSWORD"
          docker build -t nimona/nimona:$(git describe --abbrev=0) .

      - name: Release binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u=$DOCKER_USERNAME -p="$DOCKER_PASSWORD"
          cd cmd
          ../bin/goreleaser
