name: Release
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out the code
        uses: actions/checkout@v1

      - name: Publish docker container
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_GHCR_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_GHCR_PASSWORD }}
        run: |
          docker login ghcr.io -u=$DOCKER_USERNAME -p="$DOCKER_PASSWORD"
          docker build -t ghcr.io/nimona/nimona:$(git describe) .
          docker push ghcr.io/nimona/nimona:$(git describe)

      - name: Download binary tools
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib
          curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh -s v0.116.0

      - name: Release binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd cmd
          ../bin/goreleaser
