name: Go
on: create

create:
  tags:
    - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Check out the code
        uses: actions/checkout@v1

      - name: Download binary tools
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh -s v0.116.0

      - name: Release
        run: |
          cd cmd
          ../bin/goreleaser --skip-validate --rm-dist --skip-publish
