// Code generated by mockery v1.0.0. DO NOT EDIT.
package net

import mock "github.com/stretchr/testify/mock"

// MockAddressBooker is an autogenerated mock type for the AddressBooker type
type MockAddressBooker struct {
	mock.Mock
}

// CreateNewPeer provides a mock function with given fields:
func (_m *MockAddressBooker) CreateNewPeer() (*PrivatePeerInfo, error) {
	ret := _m.Called()

	var r0 *PrivatePeerInfo
	if rf, ok := ret.Get(0).(func() *PrivatePeerInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PrivatePeerInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllPeerInfo provides a mock function with given fields:
func (_m *MockAddressBooker) GetAllPeerInfo() ([]*PeerInfo, error) {
	ret := _m.Called()

	var r0 []*PeerInfo
	if rf, ok := ret.Get(0).(func() []*PeerInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*PeerInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLocalPeerInfo provides a mock function with given fields:
func (_m *MockAddressBooker) GetLocalPeerInfo() *PrivatePeerInfo {
	ret := _m.Called()

	var r0 *PrivatePeerInfo
	if rf, ok := ret.Get(0).(func() *PrivatePeerInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PrivatePeerInfo)
		}
	}

	return r0
}

// GetPeerInfo provides a mock function with given fields: peerID
func (_m *MockAddressBooker) GetPeerInfo(peerID string) (*PeerInfo, error) {
	ret := _m.Called(peerID)

	var r0 *PeerInfo
	if rf, ok := ret.Get(0).(func(string) *PeerInfo); ok {
		r0 = rf(peerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PeerInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(peerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPeerStatus provides a mock function with given fields: peerID
func (_m *MockAddressBooker) GetPeerStatus(peerID string) Status {
	ret := _m.Called(peerID)

	var r0 Status
	if rf, ok := ret.Get(0).(func(string) Status); ok {
		r0 = rf(peerID)
	} else {
		r0 = ret.Get(0).(Status)
	}

	return r0
}

// PutLocalPeerInfo provides a mock function with given fields: _a0
func (_m *MockAddressBooker) PutLocalPeerInfo(_a0 *PrivatePeerInfo) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*PrivatePeerInfo) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutPeerInfoFromBlock provides a mock function with given fields: _a0
func (_m *MockAddressBooker) PutPeerInfoFromBlock(_a0 *Block) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Block) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutPeerStatus provides a mock function with given fields: peerID, status
func (_m *MockAddressBooker) PutPeerStatus(peerID string, status Status) {
	_m.Called(peerID, status)
}
